Eight of diamonds
Jack of clubs
Ace of spades
Four of spades
Jack of diamonds
Ace of hearts
Ten of clubs
Four of clubs
Jack of hearts
Six of diamonds
Eight of hearts
Five of clubs
Ten of diamonds
Seven of hearts
Jack of spades
Four of diamonds
Nine of spades
King of hearts
Six of clubs
Three of hearts
Four of hearts
Six of spades
King of diamonds
Three of clubs
Five of hearts
King of clubs
Queen of hearts
Eight of spades
Five of spades
Ace of clubs
Ten of spades
Six of hearts
Queen of clubs
Seven of clubs
Two of diamonds
Queen of diamonds
Two of clubs
Nine of clubs
Three of spades
Nine of hearts
Ten of hearts
Three of diamonds
Seven of diamonds
King of spades
Eight of clubs
Two of spades
Two of hearts
Nine of diamonds
Ace of diamonds
Five of diamonds
Queen of spades
Seven of spades
